huaweicloud/spring-cloud-huawei

spring-cloud-servicecomb-discovery/src/main/java/org.springframework.cloud.servicecomb.discovery/client/DefaultHttpTransport.java
spring-cloud-servicecomb-discovery/src/main/java/org.springframework.cloud.servicecomb.discovery/client/HttpTransport.java
spring-cloud-servicecomb-discovery/src/main/java/org.springframework.cloud.servicecomb.discovery/client/ServiceCombClient.java
spring-cloud-servicecomb-discovery/src/main/java/org.springframework.cloud.servicecomb.discovery/client/ServiceCombClientBuilder.java
spring-cloud-servicecomb-discovery/src/test/java/org/springframework/cloud/servicecomb/discovery/client/DefaultHttpTransportTest.java
spring-cloud-servicecomb-discovery/src/test/java/org/springframework/cloud/servicecomb/discovery/client/ServiceCombClientTest.java
spring-cloud-servicecomb-discovery/src/test/java/org/springframework/cloud/servicecomb/discovery/discovery/ServiceCombDiscoveryClientTest.java

1.extract constant;
2.add unit test;

extract constant and add unit test

---

docs/config_example_zh.md
docs/config_quickstart_zh.md
docs/index.md
spring-cloud-huawei-common/src/main/java/org/springframework/cloud/common/util/MD5Util.java
spring-cloud-huawei-common/src/test/java/org/springframework/cloud/common/util/MD5UtilTest.java
spring-cloud-huawei-config/src/main/java/org/springframework/cloud/huawei/config/ConfigWatch.java
spring-cloud-huawei-config/src/main/java/org/springframework/cloud/huawei/config/ServiceCombConfigAutoConfiguration.java
spring-cloud-huawei-config/src/main/java/org/springframework/cloud/huawei/config/client/RefreshRecord.java
spring-cloud-huawei-config/src/main/java/org/springframework/cloud/huawei/config/client/ServiceCombConfigClient.java
spring-cloud-huawei-config/src/test/java/org/springframework/cloud/huawei/config/ConfigWatchTest.java

1. only when the change is refresh
2. add doc for config

modify ConfigWatch and add doc for config

---

spring-cloud-huawei-canary-core/src/main/java/org/springframework/cloud/canary/core/cache/CanaryRuleCache.java
spring-cloud-huawei-canary-core/src/main/java/org/springframework/cloud/canary/core/distribute/AbstractCanaryDistributer.java
spring-cloud-huawei-canary-core/src/main/java/org/springframework/cloud/canary/core/model/Matcher.java
spring-cloud-huawei-canary-core/src/test/java/org/springframework/cloud/canary/core/CanaryDistributerTest.java

(cherry picked from commit c867d456288e397db3ff73035e89dc8646a7aba4)

canary add test

---

spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/discovery/ServiceCombDiscoveryClientConfiguration.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/RegistryHandler.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombRegistryAutoConfiguration.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/TagsProperties.java
spring-cloud-huawei-servicecomb-discovery/src/test/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistryTest.java

[issue #71]register tags info to server center

---

spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/IpPortConfig.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/URLConfig.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/UrlConfig.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/util/URLUtil.java
spring-cloud-huawei-common/src/test/java/com/huaweicloud/common/util/URLUtilTest.java
spring-cloud-huawei-config/src/main/java/com/huaweicloud/config/client/ServiceCombConfigClient.java
spring-cloud-huawei-sample/canary-demo/canary-consumer-feign-hytrix/Dockerfile
spring-cloud-huawei-sample/canary-demo/canary-consumer-feign-hytrix/src/main/resources/application.yaml
spring-cloud-huawei-sample/canary-demo/canary-consumer-feign-hytrix/start.sh
spring-cloud-huawei-sample/canary-demo/canary-consumer/Dockerfile
spring-cloud-huawei-sample/canary-demo/canary-consumer/src/main/resources/application.yaml
spring-cloud-huawei-sample/canary-demo/canary-consumer/src/main/resources/bootstrap.yml
spring-cloud-huawei-sample/canary-demo/canary-consumer/start.sh
spring-cloud-huawei-sample/canary-demo/canary-provider-beta/Dockerfile
spring-cloud-huawei-sample/canary-demo/canary-provider-beta/src/main/resources/application.yaml
spring-cloud-huawei-sample/canary-demo/canary-provider-beta/start.sh
spring-cloud-huawei-sample/canary-demo/canary-provider/Dockerfile
spring-cloud-huawei-sample/canary-demo/canary-provider/src/main/resources/application.yaml
spring-cloud-huawei-sample/canary-demo/canary-provider/start.sh
spring-cloud-huawei-sample/discovery-demo/order-consumer/src/main/resources/application.yaml
spring-cloud-huawei-sample/dtm-demo/coupon/Dockerfile
spring-cloud-huawei-sample/dtm-demo/reserve-feign/Dockerfile
spring-cloud-huawei-sample/dtm-demo/reserve/Dockerfile
spring-cloud-huawei-sample/dtm-demo/ticket/Dockerfile
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/client/ServiceCombClient.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/discovery/ServiceCombDiscoveryClient.java

1.refactory discovery and config client. make the url List&index independent from client.
2.modify autodiscovery logic, merged some code make it more clear.
3.establish a socket connection for testing when autodiscovery .

[issue #93]refactory client

---

spring-cloud-huawei-common/pom.xml

1. jackson-dataformat-xml will add 'xml' type to content-type;
2. spring-context is useless

exclusion dependencies that cause problem

---

spring-cloud-huawei-router-client/src/main/java/com/huaweicloud/router/client/RouterWebMvcConfigurer.java
spring-cloud-huawei-router-client/src/main/java/com/huaweicloud/router/client/rest/RouterRestTemplateInterceptor.java

When reading the code, found that the word spelling error, between the coding obsessive-compulsive disorder of me, modify it

fix Interceptor spelling mistakes

---

spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/client/ServiceCombClient.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/HeartbeatScheduler.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombRegistryAutoConfiguration.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombWatcher.java
spring-cloud-huawei-servicecomb-discovery/src/test/java/com/huaweicloud/servicecomb/discovery/client/ServiceCombClientTest.java
spring-cloud-huawei-servicecomb-discovery/src/test/java/com/huaweicloud/servicecomb/discovery/registry/HeartbeatSchedulerTest.java

1. register service when retry register after heartbeat failed.
2. change heartbeat url to '' /registry/microservices/" + serviceId + "/instances/" + instanceId + "/heartbeat". 
3. websocket reconnect optimization.

[issue #296] register service when retry register / change heartbeat url

---

spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/ServiceCombAkSkProperties.java

#360 spring-cloud-huawei-common-1.5.1-Hoxton.jar使用自定义的AK/SK过程中，对AK的sha256加密使用的是加密的sk，未使用解密的sk

---

integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/GovernanceControllerIT.java
pom.xml
spring-cloud-huawei-dependencies/pom.xml
spring-cloud-huawei-swagger/src/main/java/com/huaweicloud/swagger/ServiceCombSwaggerHandlerImpl.java

update spring-boot to 2.3.5.RELEASE and spring-cloud to Hoxton.SR8
update data-bind to 2.11.3, same to the spring-boot

[#347]update spring and jaskson-databind

---

spring-cloud-huawei-config/src/main/java/com/huaweicloud/config/client/KieClient.java
spring-cloud-huawei-config/src/main/java/com/huaweicloud/config/client/kie/KieDefaultProcessor.java

Remove the automatic splicing prefix problem in the configuration & add a filter environment

#411 Remove the automatic splicing prefix problem in the configuration & add a filter environment

---

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRegistration.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/Microservice.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/ServiceCenterConfiguration.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/discovery/MicroserviceHandler.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/discovery/ServiceCombDiscoveryProperties.java
spring-cloud-huawei-servicecomb-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java

…wagger is different between local with remote ServiceCenter.

#416 modify contract and RegisterSchemaTask will not stop, when the swagger is different between local with remote ServiceCenter.

---

pom.xml
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/SpringCloudRetryExtension.java

#452 Strengthen governance and support communication and distribution capacity

---

pom.xml
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/disovery/ServiceCenterUtils.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/RBACRequestAuthHeaderProvider.java

1.Update the serviceComb dependency version
2.Modified the authentication token refreshing mechanism

# 459 Modified the authentication token refreshing mechanism

---

spring-cloud-huawei-config/src/main/java/com/huaweicloud/config/ServiceCombConfigProperties.java

[#500] ServiceCombConfigProperties中@Value不生效

[#500] ServiceCombConfigProperties中@Value不生效

---

.github/workflows/maven.yml
integration-tests/cse-v1/README.md
integration-tests/cse-v1/consumer/src/main/resources/bootstrap.yml
integration-tests/cse-v1/gateway/src/main/resources/bootstrap.yml
integration-tests/cse-v1/provider/src/main/resources/bootstrap.yml
integration-tests/cse-v2/consumer/src/main/resources/bootstrap.yml
integration-tests/cse-v2/gateway/src/main/resources/bootstrap.yml
integration-tests/cse-v2/provider/src/main/resources/bootstrap.yml
integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/OrderControllerIT.java
integration-tests/docker-build-config/pom.xml
pom.xml
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/DiscoveryBootstrapProperties.java
spring-cloud-huawei-config/src/main/java/com/huaweicloud/config/ServiceCombConfigProperties.java
spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/discovery/ServiceCombDiscoveryClient.java
spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/GovernanceConfiguration.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/SpringCloudRetryExtension.java
spring-cloud-huawei-parents/pom.xml

#add CI
#update Greenwich code

# 525 update greenwich branch

---

spring-cloud-huawei-dependencies/pom.xml
spring-cloud-starter-huawei/spring-cloud-starter-huawei-hessian/pom.xml

siged-off-by：hujinming <hujinming5@huawei.com>

[#563] Fix CVE-2021-43297

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombRegistration.java

Signed-off-by:YouLing Cheng <spadgerlin888@163.com>

[#577]optimization zuul registry

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombRegistration.java

signed-off-by:YouLing Cheng<spadgerlin888@163.com>

 [#577]optimization zuul registry

---

pmd/rulesets/bestpractices.xml
spring-cloud-starter-huawei/spring-cloud-starter-huawei-hessian/src/main/java/com/huaweicloud/hessian/HessianHttpMessageConverter.java
spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/GovernanceGatewayFilterFactory.java

#598
1.对应issue：PMD检查待修复问题-AvoidReassigningParameters #598
2.修复问题数量：5
2.增加规则：AvoidReassigningParameters

[#598]AvoidReassigningParameters

---

spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/util/MD5Util.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/util/NetUtil.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/util/VersionCompareUtil.java

Number of problems fixed: 4
From: #622

[#622]Fix problems found in PMD code check - UnusedAssignment

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/client/model/ServiceCombServiceInstance.java

From： #592 
uriEndpointObject maybe null.

[#592]The Gateway supports HTTPS routing.

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/discovery/MicroserviceHandler.java

[#629] Change health check mode to push

---

integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/GovernanceControllerIT.java
pom.xml
spring-cloud-huawei-dependencies/pom.xml
spring-cloud-starter-huawei/spring-cloud-starter-huawei-service-engine-gateway/src/main/java/com/huaweicloud/gateway/governance/GovernanceGatewayFilterFactory.java

From: #636 
1.add dependency spring-framework-bom to spring-cloud-huawei-dependencies.
2.upgrade spring-boot.version to 2.5.12.
3.upgrade spring-cloud.version to 2020.0.5.

[#636]upgrade spring and spring boot version

---

integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/GovernanceControllerIT.java
pom.xml
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/RBACRequestAuthHeaderProvider.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/ServiceCombAkSkProperties.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/ServiceCombSSLProperties.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/util/URLUtil.java
spring-cloud-huawei-dependencies/pom.xml

From: https://github.com/huaweicloud/spring-cloud-huawei/issues/636
1.add dependency spring-framework-bom to spring-cloud-huawei-dependencies.
2.upgrade spring-boot.version to 2.3.12.RELEASE.
3.upgrade spring-cloud.version to Hoxton.SR12.

[#636]upgrade spring and spring boot version 

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java

[#661] adjust heartBeatInterval to millisecond

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java

[#661]adjust heartBeatInterval to millisecond

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombAutoServiceRegistration.java

[#733]repair registe using management exception

---

spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/DiscoveryBootstrapProperties.java
spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombServiceRegistry.java

[#732]heartBeatInterval parse millis

---

spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/transport/DiscoveryBootstrapProperties.java

Signed-off-by:YouLing Cheng <spadgerlin888@163.com>

[#732]adjust bootstrapProperty healthCheckInterval default value

---

spring-cloud-huawei-discovery/src/main/java/com/huaweicloud/servicecomb/discovery/registry/ServiceCombAutoServiceRegistration.java

[#733]repair regist using management exception

---

pom.xml
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/disovery/ServiceCenterUtils.java
spring-cloud-huawei-config/src/main/java/com/huaweicloud/config/ConfigService.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/SpringCloudRetryExtension.java

[#741]update servicecomb version to 2.7.4

---

README.md
README_CN.md

- Update springboot support matrix, 2.7.0 is also supported
- Reformat the table

Update springboot support matrix

---

spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/adapters/loadbalancer/RetryAwareLoadBalancer.java

Signed-off-by: Cheng Youling<spadgerlin888@163.com>

[#947] Fix the loadBalance problem

---

spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/adapters/loadbalancer/RetryAwareLoadBalancer.java

Signed-off-by:Cheng Youling<spadgerlin888@163.com>

[#947] fixed loadbalance problem

---

integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/GovernanceControllerIT.java
integration-tests/discovery-tests/order-consumer/src/main/java/com/huaweicloud/sample/FeignService.java
integration-tests/discovery-tests/order-consumer/src/main/java/com/huaweicloud/sample/GovernanceController.java
integration-tests/discovery-tests/order-consumer/src/main/resources/application.yaml
integration-tests/discovery-tests/price-provider/src/main/java/com/huaweicloud/sample/GovernanceController.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/adapters/web/RestTemplateUtils.java

Signed-off-by: Youling Cheng <spadgerlin888@163.com>

#971 fixed target service retry governance

---

integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/GatewayIT.java
integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/GovernanceControllerIT.java
integration-tests/discovery-tests/discovery-tests-client/src/test/java/com/huaweicloud/sample/WebClientGovernanceIT.java
integration-tests/discovery-tests/gateway/src/main/resources/application.yaml
integration-tests/discovery-tests/order-consumer/src/main/java/com/huaweicloud/sample/FeignService.java
integration-tests/discovery-tests/order-consumer/src/main/java/com/huaweicloud/sample/GovernanceController.java
integration-tests/discovery-tests/order-consumer/src/main/resources/application.yaml
integration-tests/discovery-tests/price-provider/src/main/java/com/huaweicloud/sample/GovernanceController.java
spring-cloud-huawei-common/src/main/java/com/huaweicloud/common/adapters/web/FallbackClientHttpResponse.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/adapters/feign/GovernanceFeignBlockingLoadBalancerClient.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/adapters/gateway/FaultInjectionGlobalFilter.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/adapters/web/GovernanceRestTemplate.java
spring-cloud-huawei-governance/src/main/java/com/huaweicloud/governance/adapters/webclient/FaultInjectionExchangeFilterFunction.java

Signed-off-by: Youling Cheng <spadgerlin888@163.com>

#978 fixed faultInjection governance result return "null" problem

---

README.md

update Servicestage Guide link

update Servicestage Guide link

---

spring-cloud-huawei-dependencies/pom.xml

[#1214] update hessian2 version to 2.7.23

---

spring-cloud-huawei-nacos/spring-cloud-huawei-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-huawei-nacos/spring-cloud-huawei-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceLocator.java
spring-cloud-huawei-nacos/spring-cloud-huawei-nacos-config/src/main/java/com/huaweicloud/nacos/config/NacosConfigConst.java

[#1363] support default load the route header context configuration
